// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// update_pcfg_probabilities
arma::mat update_pcfg_probabilities(arma::mat& pcfg, const arma::mat& mask, const std::vector<std::vector<int>>& grammar_counter, double learning_factor);
RcppExport SEXP _Rpsge_update_pcfg_probabilities(SEXP pcfgSEXP, SEXP maskSEXP, SEXP grammar_counterSEXP, SEXP learning_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type pcfg(pcfgSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::vector<int>>& >::type grammar_counter(grammar_counterSEXP);
    Rcpp::traits::input_parameter< double >::type learning_factor(learning_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(update_pcfg_probabilities(pcfg, mask, grammar_counter, learning_factor));
    return rcpp_result_gen;
END_RCPP
}
// get_grammar_counter
std::vector<std::vector<int>> get_grammar_counter(const List& individual, const CharacterVector& non_terminals, const List& grammar);
RcppExport SEXP _Rpsge_get_grammar_counter(SEXP individualSEXP, SEXP non_terminalsSEXP, SEXP grammarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type individual(individualSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type non_terminals(non_terminalsSEXP);
    Rcpp::traits::input_parameter< const List& >::type grammar(grammarSEXP);
    rcpp_result_gen = Rcpp::wrap(get_grammar_counter(individual, non_terminals, grammar));
    return rcpp_result_gen;
END_RCPP
}
// independent_update
List independent_update(List& grammar_obj, const List& best, double learning_factor);
RcppExport SEXP _Rpsge_independent_update(SEXP grammar_objSEXP, SEXP bestSEXP, SEXP learning_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List& >::type grammar_obj(grammar_objSEXP);
    Rcpp::traits::input_parameter< const List& >::type best(bestSEXP);
    Rcpp::traits::input_parameter< double >::type learning_factor(learning_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(independent_update(grammar_obj, best, learning_factor));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rpsge_update_pcfg_probabilities", (DL_FUNC) &_Rpsge_update_pcfg_probabilities, 4},
    {"_Rpsge_get_grammar_counter", (DL_FUNC) &_Rpsge_get_grammar_counter, 3},
    {"_Rpsge_independent_update", (DL_FUNC) &_Rpsge_independent_update, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rpsge(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
