# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

recursiveMappingCpp <- function(grammar, genotype, positions, symbol, current_depth, max_depth, output, use_position_seeds = FALSE, debug_output = FALSE) {
    .Call(`_Rpsge_recursiveMappingCpp`, grammar, genotype, positions, symbol, current_depth, max_depth, output, use_position_seeds, debug_output)
}

traceRecursiveMappingWithCodon <- function(grammar, expr_codons, op_codons, var_codons) {
    .Call(`_Rpsge_traceRecursiveMappingWithCodon`, grammar, expr_codons, op_codons, var_codons)
}

