# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_pcfg_probabilities <- function(pcfg, mask, grammar_counter, learning_factor) {
    .Call(`_Rpsge_update_pcfg_probabilities`, pcfg, mask, grammar_counter, learning_factor)
}

get_grammar_counter <- function(individual, non_terminals, grammar) {
    .Call(`_Rpsge_get_grammar_counter`, individual, non_terminals, grammar)
}

independent_update <- function(grammar_obj, best, learning_factor) {
    .Call(`_Rpsge_independent_update`, grammar_obj, best, learning_factor)
}

